### ISSUE TITLE
Why are armors/weapons always +15 upgraded?

### ISSUE THREAD

**Issue by bobhacker** [atomicptr/dauntless-builder-reforged#111]
Please, it makes no sense for starter/early-game builds...

See:
https://www.dauntless-builder.com/b/JwU8CoCxLIkU7F7TQTJTdTETdCmCK2IOHECR1IniAC3OfvIeCO0fLtNY

It gives you +7 perks, which is useless.

Thanks.

**Comment by atomicptr** [comment]
I think it's a sensible default, because the vast majority of builds are for endgame. Tho, I think what you want is an ability to change the level of an item which you can do via this thing here:

![image](https://user-images.githubusercontent.com/674705/61215758-02cdd200-a70c-11e9-83c1-8b5a6d052741.png)

**Comment by bobhacker** [comment]
Thanks, I think the creator didn't know... I'll do it for myself! ;)
