### ISSUE TITLE
Split the base data into a separate package

### ISSUE THREAD

**Issue by adaliszk** [atomicptr/dauntless-builder-reforged#116]
It would be really great if the base data would be separated into a package for letting experiments like reverse build calculation work from your data. This decoupling could be very useful for you because more contributors would able to help to maintain this clear section of the project.

**Comment by atomicptr** [comment]
I don't see the advantage of having the data in a package, is there anything that you can't do by just accessing the data via HTTP ( https://www.dauntless-builder.com/data.json )?

I'd even argue for most tools this would be a fairly bad idea as you have to update your dependencies in order to get a new version which creates an unnecessary extra step of work to tools.

Someone asked me this before for a different project (similar circumstance tho) where I answered this: https://github.com/WFCD/warframe-drop-data/issues/27#issuecomment-401794841

**Comment by atomicptr** [comment]
Closing this because as I've mentioned it's easier to just pull the data directly via HTTP.
