### ISSUE TITLE
Small bug with Malkarion hands armor icon

### ISSUE THREAD

**Issue by siddagra** [atomicptr/dauntless-builder-reforged#146]
![image](https://user-images.githubusercontent.com/52118936/79816602-3f1c1600-83a1-11ea-8186-b00cf9354c27.png)
The image seems to be flipped compared to all other hand armor icons. Not sure if this is a bug or intended.

**Comment by atomicptr** [comment]
Interesting, this is probably due to Cloudflare as the file seems to be correct https://github.com/atomicptr/dauntless-builder/blob/master/assets/icons/armours/malkarion/MalkarionsGrasp.png

Lets clear that cache...

Should be fixed now:

![image](https://user-images.githubusercontent.com/674705/79831608-03387f00-83a8-11ea-92fe-99a84c2810c6.png)

Thanks for the report!
