### ISSUE TITLE
Omnicell Update 1.7.0

### ISSUE THREAD

**Issue by SunlightBro** [atomicptr/dauntless-builder-reforged#187]
### Data Update

With the addition of Omnicells 1.7.0, I think most current builds will break.
So I guess my question/discussion is: 
Whats your plan on updating the [data](https://www.dauntless-builder.com/data.json) models? 

- new model for `omnicell`?
- `lantern_ability` could be just a String, no map needed if there are no `instant` and `hold` anymore.
- are you considering deprecating/updating some old models 
e.g: weapons `power` back then was a map 
{1-15: 20-550} but since reforged this could be simplified, same with armour resistance.
_(but that would probably also impact perks)_

- Updates on how the url hash for a build will be generated/parsed?

I'm working with your data in a mobile-app so I just wanna know what your plan is so I can make the necessary changes as well.

**Comment by atomicptr** [comment]
I can't tell you exactly how I'll add them yet, but as with the past I try to avoid any breakages if possible which is why as you've pointed out the new power scale is a bit odd and certainly could be simplified but that would break other apps which I don't want to do. 

Since I can't use an unused field like I did with the bond weapons (That field was reserved for a possible second mod for repeaters as PhxLabs wasn't very clear on this back then) I'll have to up the version (to 4 now) and create a new format for the hash. Since I can detect users with an old build URL I might be able to do some conversions (keep build, but unequip removed cells for instance) but we'll see.

**Comment by SunlightBro** [comment]
Get your Point. 
imho with major changes _(like v.4 now)_, when everyone who uses your app/data/tool and builds upon it, has to make upgrades anyway, you shouldn't have to hesitate to introduce changes.
If they are documented in a changelog/readme so everyone can retrace and comprehend them it's fine.

If any help is wanted, lemme know. 🚀

**Comment by atomicptr** [comment]
Since Dauntless Builder is now updated and contains the new data I'll close this.

The source of truth for what data is in the hash is still the source code https://github.com/atomicptr/dauntless-builder/blob/master/src/models/BuildModel.jsx#L8 eventually I'll update the documentation :sweat_smile:.
