### ISSUE TITLE
Phaelanx Gear

### ISSUE THREAD

**Issue by NathalieWK** [atomicptr/dauntless-builder-reforged#206]
https://dauntless.fandom.com/wiki/Phaelanx%27s_Spearhead
https://dauntless.fandom.com/wiki/Phaelanx%27s_Vanguard
https://dauntless.fandom.com/wiki/Phaelanx%27s_Firearms
https://dauntless.fandom.com/wiki/Phaelanx%27s_Heatsinks

https://dauntless.fandom.com/wiki/Fists_of_the_Firebird
https://dauntless.fandom.com/wiki/Call_of_the_Firebird
https://dauntless.fandom.com/wiki/Talons_of_the_Firebird
https://dauntless.fandom.com/wiki/Rage_of_the_Firebird
https://dauntless.fandom.com/wiki/Eyes_of_the_Firebird
https://dauntless.fandom.com/wiki/Shriek_of_the_Firebird
https://dauntless.fandom.com/wiki/Fate_of_the_Firebird

**Comment by atomicptr** [comment]
Due to the wiki being wrong most of the time in the past I don't quite like to use them as a source, I've attached some ingame screenshots

# Weapons

![image](https://user-images.githubusercontent.com/674705/132805077-29a57233-f3c8-4817-9c05-5f5e67945bb2.png)
![image](https://user-images.githubusercontent.com/674705/132805091-6937f90e-2a90-4664-8ace-28c683bc9c48.png)
![image](https://user-images.githubusercontent.com/674705/132805104-69204fe3-1010-40e5-8242-eef5b0ccd944.png)
![image](https://user-images.githubusercontent.com/674705/132805113-f59fde06-32c4-4f65-a02d-0f5c385db186.png)
![image](https://user-images.githubusercontent.com/674705/132805137-c63d392c-f756-40a6-a153-c339e0ab4cad.png)
![image](https://user-images.githubusercontent.com/674705/132805166-3cd17ad0-af30-4b80-ab02-fcd8b1052582.png)
![image](https://user-images.githubusercontent.com/674705/132805201-4f47ef23-d159-4b55-aee0-0aabd9df1660.png)

# Armor

![image](https://user-images.githubusercontent.com/674705/132805267-5a721e71-b563-4b7c-9c05-03d3cf86e7fc.png)
![image](https://user-images.githubusercontent.com/674705/132805284-6b00a384-3908-48c7-96c7-0d52161d5ec6.png)
![image](https://user-images.githubusercontent.com/674705/132805295-d17e2ca4-91ee-405f-99a7-a0b9f7128d29.png)
![image](https://user-images.githubusercontent.com/674705/132805309-6cc0c4e9-7a15-42f8-9ed2-4b4103244ffc.png)
