### ISSUE TITLE
I had 30 or more builds yesterday, poof only 5 remain.

### ISSUE THREAD

**Issue by ghost** [atomicptr/dauntless-builder-reforged#52]
I had 30 or more builds yesterday, poof only 5 builds remain.

I don't know what happened or what the solution is.

I am just saying my collections of builds are gone, and I don't know how to get them back.

To be clear, the many builds that I created are not in "MY BUILDS" ; however, about five remain.

The ones that I bookmarked are still online and exist, so I am not saying that the builds are gone.

I am saying my large list of "MY BUILDS" is no longer large.

**Comment by atomicptr** [comment]
Hm, this sounds like you might have either changed your browser or deleted all browser data recently, the data for my builds is stored in something called local storage which is attached to your browser data. I don't have any control over this. Also builds that you've bookmarked are "still online", because they're fully client sided as well ;).

**Comment by atomicptr** [comment]
Since there was no response, I assume that this is resolved.
